import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Tag from '#models/tag'

export default class extends BaseSeeder {
  datas = [
    {
      id: 999999,
      name: 'tag_name_for_testing',
      parentId: null,
      main: 10,
      weight: 10,
    },
    {
      id: 1,
      name: 'Autre',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2,
      name: 'Aberration de conduction',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3,
      name: 'Amiodarone',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 7,
      name: 'Artefact (spike) de stimulation atriale',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 8,
      name: 'Artefact (spike) de stimulation ventriculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 9,
      name: 'Arythmie respiratoire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 10,
      name: 'Aspect S1Q3',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 11,
      name: 'Axe droit',
      parentId: 2860,
      main: 1,
      weight: 1.5,
    },
    {
      id: 12,
      name: 'Axe extrême',
      parentId: 2860,
      main: 1,
      weight: 1.5,
    },
    {
      id: 13,
      name: 'Axe gauche',
      parentId: 2860,
      main: 1,
      weight: 1.5,
    },
    {
      id: 14,
      name: 'Axe normal',
      parentId: 2860,
      main: 1,
      weight: 1.5,
    },
    {
      id: 18,
      name: 'Bruit',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 19,
      name: 'Coeur sain',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 20,
      name: 'Complexe de capture',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 21,
      name: 'Complexe de fusion',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 22,
      name: 'Concordance négative',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 23,
      name: 'Concordance positive',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 31,
      name: 'Cupule digitalique',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 34,
      name: 'Déplacement de sonde',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 35,
      name: 'Dissociation atrio-ventriculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 36,
      name: 'Dissociation isorythmique',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 37,
      name: 'Distorsion terminale',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 40,
      name: 'Dualité nodale',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 42,
      name: 'Elevation point J',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 51,
      name: 'Fibre atrio-fasciculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 52,
      name: 'Fibre atrio-ventriculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 53,
      name: 'Fibre nodo-fasciculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 54,
      name: 'Fibre nodo-ventriculaire',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 56,
      name: 'Flutter Flécainide',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 64,
      name: 'Hypomagnésémie',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 70,
      name: 'Lithium',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 71,
      name: 'Manœuvres vagales',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 75,
      name: 'Onde delta',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 96,
      name: 'Onde U',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 98,
      name: 'Période de Luciani-Wenckebach',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 103,
      name: 'QRS fins',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 105,
      name: 'Quinidine',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 106,
      name: 'Resynchronisation épicardique chirurgicale',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 112,
      name: 'Sous-décalage segment PQ',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 139,
      name: 'Syndrome coronaire aigü (SCA)',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 145,
      name: 'Tachycardie supra-ventriculaire (TSV)',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 148,
      name: "Test à l'adénosine",
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
    {
      id: 156,
      name: 'Anomalie de la qualité du tracé',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 157,
      name: 'Artéfacts',
      parentId: 156,
      main: 1,
      weight: 1.5,
    },
    {
      id: 158,
      name: "Inversion d'électrodes",
      parentId: 156,
      main: 1,
      weight: 1.5,
    },
    {
      id: 159,
      name: 'frontales',
      parentId: 158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 160,
      name: 'précordiales',
      parentId: 158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 161,
      name: 'onde P et QRS négatif DI',
      parentId: 158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 162,
      name: 'tracé plat en DI, DII ou DIII',
      parentId: 158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 163,
      name: 'onde P, QRS et T négatif en DIII',
      parentId: 158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 164,
      name: 'ECG reconstruit',
      parentId: 156,
      main: 1,
      weight: 1.5,
    },
    {
      id: 165,
      name: 'Algorithme EASI',
      parentId: 164,
      main: 1,
      weight: 1.5,
    },
    {
      id: 166,
      name: 'Algorithme GE',
      parentId: 164,
      main: 1,
      weight: 1.5,
    },
    {
      id: 167,
      name: 'Algorithme autre/inconnu',
      parentId: 164,
      main: 1,
      weight: 1.5,
    },
    {
      id: 168,
      name: 'Rythme',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 169,
      name: 'Rythme sinusal normal (Activité sinusale conduite aux ventricules)',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 171,
      name: 'Activité sinusale (onde P sinusale)',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 173,
      name: 'Anomalie de conduction',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 174,
      name: 'Bradycardie (FC < 60 bpm)',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 175,
      name: 'Bradycardie sinusale',
      parentId: 174,
      main: 1,
      weight: 1.5,
    },
    {
      id: 176,
      name: 'appropriée à la clinique',
      parentId: 175,
      main: 1,
      weight: 1.5,
    },
    {
      id: 179,
      name: 'Asystole',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 182,
      name: 'Dysfonction sinusale / Bloc sino atrial (BSA)',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 183,
      name: 'Bradycardie sinusale pathologique',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 186,
      name: 'Bloc sino atrial (BSA) de type 1',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 188,
      name: 'Bloc sino atrial (BSA) de type 2 (onde P manquante)',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 191,
      name: 'Bloc sino atrial (BSA) de type 3 (onde P inexistante) ou paralysie sinusale',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 194,
      name: 'Pause sinusale (> 3 sec)',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 198,
      name: 'Pause post réduction de tachycardie',
      parentId: 182,
      main: 1,
      weight: 1.5,
    },
    {
      id: 204,
      name: 'Anomalie de la conduction AV',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 205,
      name: 'BAV 1',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 206,
      name: 'BAV 2 Mobitz 1',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 209,
      name: 'BAV 2 : 1',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 211,
      name: 'BAV 2 Mobitz 2 (onde P bloquée inopinée)',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 213,
      name: 'BAV 3 : 1 ou plus ou FA très lente',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 215,
      name: 'BAV 3 / complet',
      parentId: 204,
      main: 1,
      weight: 1.5,
    },
    {
      id: 220,
      name: 'Bloc de branche',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 221,
      name: 'Bloc de branche droit (BBD) incomplet',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 225,
      name: 'Bloc de branche droit (BBD) complet',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 227,
      name: 'Bloc fasciculaire antérieur gauche (BFAG ou HBAG)',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 231,
      name: 'Bloc fasciculaire postérieur gauche (BFPG ou HBPG)',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 235,
      name: 'Bloc de branche gauche incomplet',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 237,
      name: 'Bloc de branche gauche complet (BBG)',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 239,
      name: 'Bloc indifférencié',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 241,
      name: 'Bloc bifasciculaire',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 246,
      name: 'Bloc alternant',
      parentId: 220,
      main: 1,
      weight: 1.5,
    },
    {
      id: 249,
      name: 'PR court',
      parentId: 173,
      main: 1,
      weight: 1.5,
    },
    {
      id: 255,
      name: 'Pré-excitation',
      parentId: 249,
      main: 1,
      weight: 1.5,
    },
    {
      id: 259,
      name: 'antéro-latérale gauche',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 263,
      name: 'postéro-latérale gauche',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 267,
      name: 'postéro-septale gauche',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 271,
      name: 'postéro-septale droite',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 275,
      name: 'antéro-septale droite',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 279,
      name: 'postéro-latérale droite',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 283,
      name: 'antéro-latérale droite',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 287,
      name: 'de type Mahaim',
      parentId: 255,
      main: 1,
      weight: 1.5,
    },
    {
      id: 290,
      name: 'Anomalie de rythme',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 291,
      name: 'Tachycardie (FC > 100 bpm)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 292,
      name: 'Tachycardie sinusale',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 293,
      name: 'appropriée à la clinique',
      parentId: 292,
      main: 1,
      weight: 1.5,
    },
    {
      id: 294,
      name: 'inappropriée à la clinique',
      parentId: 292,
      main: 1,
      weight: 1.5,
    },
    {
      id: 295,
      name: 'Tachycardie à QRS fins réguliers',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 302,
      name: 'Tachycardie à QRS fins irréguliers',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 308,
      name: 'Tachycardie à QRS larges réguliers monomorphes',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 323,
      name: 'Tachycardie à QRS larges irréguliers monomorphes',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 338,
      name: 'Tachycardie à QRS larges irréguliers polymorphes',
      parentId: 291,
      main: 1,
      weight: 1.5,
    },
    {
      id: 345,
      name: 'Fibrillation ventriculaire',
      parentId: 338,
      main: 1,
      weight: 1.5,
    },
    {
      id: 346,
      name: 'Torsade de pointe',
      parentId: 338,
      main: 1,
      weight: 1.5,
    },
    {
      id: 347,
      name: 'SuperWolf (Fibrillation atriale + pré-excitation)',
      parentId: 338,
      main: 1,
      weight: 1.5,
    },
    {
      id: 351,
      name: 'Flutter atrial',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 352,
      name: 'Flutter atrial typique',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 353,
      name: 'Flutter anti-horaire (commun)',
      parentId: 352,
      main: 1,
      weight: 1.5,
    },
    {
      id: 354,
      name: 'conduction 1/1',
      parentId: 353,
      main: 1,
      weight: 1.5,
    },
    {
      id: 355,
      name: 'conduction 2/1',
      parentId: 353,
      main: 1,
      weight: 1.5,
    },
    {
      id: 356,
      name: 'conduction variable',
      parentId: 353,
      main: 1,
      weight: 1.5,
    },
    {
      id: 357,
      name: 'conduction lente',
      parentId: 353,
      main: 1,
      weight: 1.5,
    },
    {
      id: 362,
      name: 'Flutter horaire',
      parentId: 352,
      main: 1,
      weight: 1.5,
    },
    {
      id: 363,
      name: 'conduction 1/1',
      parentId: 362,
      main: 1,
      weight: 1.5,
    },
    {
      id: 364,
      name: 'conduction 2/1',
      parentId: 362,
      main: 1,
      weight: 1.5,
    },
    {
      id: 365,
      name: 'conduction variable',
      parentId: 362,
      main: 1,
      weight: 1.5,
    },
    {
      id: 366,
      name: 'conduction lente',
      parentId: 362,
      main: 1,
      weight: 1.5,
    },
    {
      id: 371,
      name: 'conduction 1/1',
      parentId: 352,
      main: 1,
      weight: 1.5,
    },
    {
      id: 372,
      name: 'conduction 2/1',
      parentId: 352,
      main: 1,
      weight: 1.5,
    },
    {
      id: 373,
      name: 'conduction variable',
      parentId: 352,
      main: 1,
      weight: 1.5,
    },
    {
      id: 379,
      name: 'Flutter atrial atypique',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 380,
      name: 'conduction 1/1',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 381,
      name: 'conduction 2/1',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 382,
      name: 'conduction variable',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 383,
      name: 'conduction lente',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 391,
      name: 'Flutter atypique droit',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 392,
      name: 'conduction 1/1',
      parentId: 391,
      main: 1,
      weight: 1.5,
    },
    {
      id: 393,
      name: 'conduction 2/1',
      parentId: 391,
      main: 1,
      weight: 1.5,
    },
    {
      id: 394,
      name: 'conduction variable',
      parentId: 391,
      main: 1,
      weight: 1.5,
    },
    {
      id: 395,
      name: 'conduction lente',
      parentId: 391,
      main: 1,
      weight: 1.5,
    },
    {
      id: 403,
      name: 'Flutter atypique gauche',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 404,
      name: 'conduction 1/1',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 405,
      name: 'conduction 2/1',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 406,
      name: 'conduction variable',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 407,
      name: 'conduction lente',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 415,
      name: 'conduction 1/1',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 416,
      name: 'conduction 2/1',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 417,
      name: 'conduction variable',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 418,
      name: 'conduction lente',
      parentId: 351,
      main: 1,
      weight: 1.5,
    },
    {
      id: 423,
      name: 'Tachycardie atriale',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 424,
      name: 'conduction 1/1',
      parentId: 423,
      main: 1,
      weight: 1.5,
    },
    {
      id: 425,
      name: 'conduction 2/1',
      parentId: 423,
      main: 1,
      weight: 1.5,
    },
    {
      id: 426,
      name: 'conduction variable',
      parentId: 423,
      main: 1,
      weight: 1.5,
    },
    {
      id: 427,
      name: 'conduction lente',
      parentId: 423,
      main: 1,
      weight: 1.5,
    },
    {
      id: 432,
      name: 'Fibrillation atriale (FA)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 434,
      name: 'grosses mailles',
      parentId: 432,
      main: 1,
      weight: 1.5,
    },
    {
      id: 435,
      name: 'petites mailles',
      parentId: 432,
      main: 1,
      weight: 1.5,
    },
    {
      id: 436,
      name: 'conduction lente',
      parentId: 432,
      main: 1,
      weight: 1.5,
    },
    {
      id: 443,
      name: 'Tachycardie jonctionnelle',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 444,
      name: 'Tachycardie par réentrée intranodale',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 445,
      name: 'slow fast',
      parentId: 444,
      main: 1,
      weight: 1.5,
    },
    {
      id: 446,
      name: 'slow slow',
      parentId: 444,
      main: 1,
      weight: 1.5,
    },
    {
      id: 447,
      name: 'fast slow',
      parentId: 444,
      main: 1,
      weight: 1.5,
    },
    {
      id: 452,
      name: 'Tachycardie par réentrée sur voie accessoire à conduction décrémentielle (de Coumel)',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 456,
      name: 'Tachycardie par réentrée sur voie accessoire à conduction décrémentielle (sur fibre de Mahaim)',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 460,
      name: 'Tachycardie par réentrée sur voie accessoire orthodromique',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 464,
      name: 'Tachycardie par réentrée sur voie accessoire antidromique',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 468,
      name: 'Tachycardie jonctionnelle ectopique (JET) ou tachycardie automatique',
      parentId: 443,
      main: 1,
      weight: 1.5,
    },
    {
      id: 471,
      name: 'Double réponse ventriculaire (double conduction nodale)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 472,
      name: 'Tachycardie ventriculaire (TV)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 473,
      name: 'Tachycardie ventriculaire (TV) sur séquelle de nécrose',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 474,
      name: 'gauche',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 475,
      name: 'droite',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 476,
      name: 'basale',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 477,
      name: 'médiane',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 478,
      name: 'apicale',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 479,
      name: 'inférieure',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 480,
      name: 'antérieure',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 481,
      name: 'septale',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 482,
      name: 'latérale',
      parentId: 473,
      main: 1,
      weight: 1.5,
    },
    {
      id: 483,
      name: 'Tachycardie ventriculaire (TV) sur coeur sain',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 484,
      name: 'infundibulaire',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 485,
      name: 'fasciculaire',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 486,
      name: 'de pillier',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 487,
      name: 'croix du coeur',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 488,
      name: 'péri-hissienne',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 489,
      name: 'gauche',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 490,
      name: 'droite',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 491,
      name: 'basale',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 492,
      name: 'médiane',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 493,
      name: 'apicale',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 494,
      name: 'inférieure',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 495,
      name: 'antérieure',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 496,
      name: 'septale',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 497,
      name: 'latérale',
      parentId: 483,
      main: 1,
      weight: 1.5,
    },
    {
      id: 498,
      name: 'Tachycardie ventriculaire (TV) sur cardiopathie non ischémique',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 499,
      name: 'de branche à branche',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 500,
      name: 'epicardique',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 501,
      name: 'gauche',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 502,
      name: 'droite',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 503,
      name: 'basale',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 504,
      name: 'médiane',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 505,
      name: 'apicale',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 506,
      name: 'inférieure',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 507,
      name: 'antérieure',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 508,
      name: 'septale',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 509,
      name: 'latérale',
      parentId: 498,
      main: 1,
      weight: 1.5,
    },
    {
      id: 510,
      name: 'Flutter ventriculaire',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 511,
      name: 'gauche',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 512,
      name: 'droite',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 513,
      name: 'basale',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 514,
      name: 'médiane',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 515,
      name: 'apicale',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 516,
      name: 'inférieure',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 517,
      name: 'antérieure',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 518,
      name: 'septale',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 519,
      name: 'latérale',
      parentId: 510,
      main: 1,
      weight: 1.5,
    },
    {
      id: 520,
      name: 'Tachycardie ventriculaire (TV) bidirectionnelle',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 521,
      name: 'Tachycardie ventriculaire (TV) polymorphe',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 522,
      name: 'gauche',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 523,
      name: 'droite',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 524,
      name: 'basale',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 525,
      name: 'médiane',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 526,
      name: 'apicale',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 527,
      name: 'inférieure',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 528,
      name: 'antérieure',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 529,
      name: 'septale',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 530,
      name: 'latérale',
      parentId: 472,
      main: 1,
      weight: 1.5,
    },
    {
      id: 537,
      name: 'Tachycardie ventriculaire non soutenue (TVNS)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 538,
      name: 'monomorphe',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 539,
      name: 'polymorphe',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 540,
      name: 'gauche',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 541,
      name: 'droite',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 542,
      name: 'basale',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 543,
      name: 'médiane',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 544,
      name: 'apicale',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 545,
      name: 'inférieure',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 546,
      name: 'antérieure',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 547,
      name: 'septale',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 548,
      name: 'latérale',
      parentId: 537,
      main: 1,
      weight: 1.5,
    },
    {
      id: 550,
      name: 'Rythme idioventriculaire accéléré (RIVA)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 551,
      name: 'Rythme idioventriculaire accéléré (RIVA) post reperfusion coronaire',
      parentId: 550,
      main: 1,
      weight: 1.5,
    },
    {
      id: 554,
      name: 'Rythme idiojonctionnel accéléré (RIJA)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 555,
      name: 'Rythme idiojonctionnel accéléré (RIJA) post ablation de la voie lente',
      parentId: 554,
      main: 1,
      weight: 1.5,
    },
    {
      id: 557,
      name: 'Rythme idiojonctionnel accéléré (RIJA) induit par cathécholamine',
      parentId: 554,
      main: 1,
      weight: 1.5,
    },
    {
      id: 559,
      name: 'Rythme idiojonctionnel accéléré (RIJA) post reperfusion coronaire',
      parentId: 554,
      main: 1,
      weight: 1.5,
    },
    {
      id: 562,
      name: 'Extrasystoles supraventriculaires (ESSV)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 563,
      name: 'Extrasystoles atrial (ESA)',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 570,
      name: 'Extrasystoles jonctionnelles (ESJ)',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 583,
      name: 'Extrasystoles ventriculaires (ESV)',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 584,
      name: 'Extrasystoles ventriculaires (ESV) infundibulaire VD',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 589,
      name: 'couplage court',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 590,
      name: 'couplage long',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 603,
      name: 'Extrasystoles ventriculaires (ESV) du ventricule droit (autre que infundibulaire)',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 608,
      name: 'couplage court',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 609,
      name: 'couplage long',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 614,
      name: 'basale',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 615,
      name: 'médiane',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 616,
      name: 'apicale',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 617,
      name: 'inférieure',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 618,
      name: 'antérieure',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 619,
      name: 'septale',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 620,
      name: 'latérale',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 622,
      name: 'Extrasystoles ventriculaires (ESV) de pillier',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 627,
      name: 'couplage court',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 628,
      name: 'couplage long',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 638,
      name: 'septale',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 639,
      name: 'latérale',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 641,
      name: 'Extrasystoles ventriculaires (ESV) infundibulaire VG (de cusp)',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 646,
      name: 'couplage court',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 647,
      name: 'couplage long',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 660,
      name: 'Extrasystoles ventriculaires (ESV) de la jonction mitro-aortique',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 665,
      name: 'couplage court',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 666,
      name: 'couplage long',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 679,
      name: 'Extrasystoles ventriculaires (ESV) fasciculaire',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 684,
      name: 'couplage court',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 685,
      name: 'couplage long',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 694,
      name: 'antérieure',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 695,
      name: 'postérieure',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 698,
      name: 'Extrasystoles ventriculaires (ESV) du Purkinje',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 703,
      name: 'couplage court',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 704,
      name: 'couplage long',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 707,
      name: 'gauche',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 708,
      name: 'droite',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 709,
      name: 'basale',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 710,
      name: 'médiane',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 711,
      name: 'apicale',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 712,
      name: 'inférieure',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 713,
      name: 'antérieure',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 714,
      name: 'septale',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 715,
      name: 'latérale',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 717,
      name: 'Extrasystoles ventriculaires (ESV) du sommet du VG',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 722,
      name: 'couplage court',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 723,
      name: 'couplage long',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 740,
      name: 'couplage court',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 741,
      name: 'couplage long',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 744,
      name: 'gauche',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 745,
      name: 'droite',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 746,
      name: 'basale',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 747,
      name: 'médiane',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 748,
      name: 'apicale',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 749,
      name: 'inférieure',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 750,
      name: 'antérieure',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 751,
      name: 'septale',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 752,
      name: 'latérale',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 754,
      name: 'Wandering pacemaker',
      parentId: 290,
      main: 1,
      weight: 1.5,
    },
    {
      id: 755,
      name: 'Electro-entrainement / Pacemaker / Défibrillateur (stimulation)',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 756,
      name: 'Stimulation atriale',
      parentId: 755,
      main: 1,
      weight: 1.5,
    },
    {
      id: 758,
      name: 'Stimulation ventriculaire',
      parentId: 755,
      main: 1,
      weight: 1.5,
    },
    {
      id: 759,
      name: 'Stimulation ventriculaire droite',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 760,
      name: 'Stimulation ventriculaire gauche',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 761,
      name: 'Stimulation de resynchronisation biventriculaire',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 762,
      name: 'négativité DI',
      parentId: 761,
      main: 1,
      weight: 1.5,
    },
    {
      id: 764,
      name: 'Stimulation hissienne sélective',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 765,
      name: 'Stimulation hissienne non sélective',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 766,
      name: 'Stimulation de branche gauche sélective',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 767,
      name: 'Stimulation de branche gauche non sélective',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 768,
      name: 'Stimulation septal profonde',
      parentId: 758,
      main: 1,
      weight: 1.5,
    },
    {
      id: 770,
      name: 'Cardioversion',
      parentId: 755,
      main: 1,
      weight: 1.5,
    },
    {
      id: 771,
      name: 'Cardioversion TSV inefficace',
      parentId: 770,
      main: 1,
      weight: 1.5,
    },
    {
      id: 772,
      name: 'Cardioversion TV/FV inefficace',
      parentId: 770,
      main: 1,
      weight: 1.5,
    },
    {
      id: 773,
      name: 'Dysfonction de pacemaker',
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 774,
      name: 'Tachycardie electroentrainée',
      parentId: 773,
      main: 1,
      weight: 1.5,
    },
    {
      id: 775,
      name: 'Tachycardie par réentrée electronique',
      parentId: 774,
      main: 1,
      weight: 1.5,
    },
    {
      id: 776,
      name: 'Tachycardie par défaut de repli',
      parentId: 774,
      main: 1,
      weight: 1.5,
    },
    {
      id: 777,
      name: "Tachycardie electroentrainée sur suivi d'une TSV lente",
      parentId: 774,
      main: 1,
      weight: 1.5,
    },
    {
      id: 778,
      name: 'Défaut de capture',
      parentId: 773,
      main: 1,
      weight: 1.5,
    },
    {
      id: 779,
      name: 'Artefact (spike) de stimulation sans capture atriale',
      parentId: 778,
      main: 1,
      weight: 1.5,
    },
    {
      id: 781,
      name: 'Artefact (spike) de stimulation sans capture ventriculaire',
      parentId: 778,
      main: 1,
      weight: 1.5,
    },
    {
      id: 784,
      name: "Bradycardie en présence d'un stimulateur cardiaque",
      parentId: 773,
      main: 1,
      weight: 1.5,
    },
    {
      id: 785,
      name: 'Surdétection',
      parentId: 784,
      main: 1,
      weight: 1.5,
    },
    {
      id: 787,
      name: 'Algorithme de conservation de la conduction',
      parentId: 784,
      main: 1,
      weight: 1.5,
    },
    {
      id: 790,
      name: 'Excès de stimulation',
      parentId: 773,
      main: 1,
      weight: 1.5,
    },
    {
      id: 792,
      name: "Défaut d'écoute",
      parentId: 790,
      main: 1,
      weight: 1.5,
    },
    {
      id: 794,
      name: 'Stimulation en fenêtre de sécurité',
      parentId: 790,
      main: 1,
      weight: 1.5,
    },
    {
      id: 796,
      name: "Rythme d'échappement",
      parentId: 168,
      main: 1,
      weight: 1.5,
    },
    {
      id: 799,
      name: 'Echappement atrial',
      parentId: 796,
      main: 1,
      weight: 1.5,
    },
    {
      id: 801,
      name: 'Echappement jonctionnel',
      parentId: 796,
      main: 1,
      weight: 1.5,
    },
    {
      id: 804,
      name: 'Echappement ventriculaire',
      parentId: 796,
      main: 1,
      weight: 1.5,
    },
    {
      id: 807,
      name: 'Anomalie de la morphologie onde P',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 808,
      name: 'Hypertrophie atriale',
      parentId: 807,
      main: 1,
      weight: 1.5,
    },
    {
      id: 809,
      name: 'Hypertrophie atriale gauche (HAG)',
      parentId: 808,
      main: 1,
      weight: 1.5,
    },
    {
      id: 812,
      name: 'Hypertrophie atriale droite (HAD)',
      parentId: 808,
      main: 1,
      weight: 1.5,
    },
    {
      id: 817,
      name: 'Bloc de conduction intra-atrial',
      parentId: 807,
      main: 1,
      weight: 1.5,
    },
    {
      id: 818,
      name: 'Activité atriale basse (onde P non positive en DII-VF)',
      parentId: 807,
      main: 1,
      weight: 1.5,
    },
    {
      id: 819,
      name: 'Rythme du sinus coronaire',
      parentId: 818,
      main: 1,
      weight: 1.5,
    },
    {
      id: 820,
      name: 'Onde P rétrograde',
      parentId: 807,
      main: 1,
      weight: 1.5,
    },
    {
      id: 821,
      name: 'Anomalie de la morphologie QRS',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 822,
      name: 'Onde Q pathologique',
      parentId: 821,
      main: 1,
      weight: 1.5,
    },
    {
      id: 823,
      name: 'antérieure',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 824,
      name: 'septale (V1-V2)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 825,
      name: 'apicale (V3-V4)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 826,
      name: 'latérale bas (V5-V6)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 827,
      name: 'latérale haut (DI-aVL)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 828,
      name: 'inférieure (DIII-VF-DII)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 829,
      name: 'postéro-basale (V7-V8-V9)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 830,
      name: 'droite (V3R V4R)',
      parentId: 822,
      main: 1,
      weight: 1.5,
    },
    {
      id: 831,
      name: 'QRS larges',
      parentId: 821,
      main: 1,
      weight: 1.5,
    },
    {
      id: 838,
      name: 'Modification ischémique aiguë des QRS',
      parentId: 821,
      main: 1,
      weight: 1.5,
    },
    {
      id: 839,
      name: 'fragmentation',
      parentId: 838,
      main: 1,
      weight: 1.5,
    },
    {
      id: 843,
      name: 'Amplitude anormale des QRS',
      parentId: 821,
      main: 1,
      weight: 1.5,
    },
    {
      id: 844,
      name: 'Hypertrophie ventriculaire gauche (HVG)',
      parentId: 843,
      main: 1,
      weight: 1.5,
    },
    {
      id: 845,
      name: 'Indice de Sokolow > 35 mm (> 45 mm avant 40 ans)',
      parentId: 844,
      main: 1,
      weight: 1.5,
    },
    {
      id: 847,
      name: 'Indice de Cornell > 28 mm (H); > 20 mm (F)',
      parentId: 844,
      main: 1,
      weight: 1.5,
    },
    {
      id: 850,
      name: 'Hypertrophie ventriculaire droite (HVD)',
      parentId: 843,
      main: 1,
      weight: 1.5,
    },
    {
      id: 851,
      name: 'Microvoltage',
      parentId: 843,
      main: 1,
      weight: 1.5,
    },
    {
      id: 852,
      name: 'Microvoltage diffus',
      parentId: 851,
      main: 1,
      weight: 1.5,
    },
    {
      id: 855,
      name: 'Rabotage/écrêtage des ondes R en antérieur',
      parentId: 843,
      main: 1,
      weight: 1.5,
    },
    {
      id: 856,
      name: 'Anomalie de repolarisation du point J ou du segment ST',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 857,
      name: 'Variante de la normale',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 858,
      name: 'Sus-décalage physiologique antérieur',
      parentId: 857,
      main: 1,
      weight: 1.5,
    },
    {
      id: 859,
      name: 'septal (V1-V2)',
      parentId: 858,
      main: 1,
      weight: 1.5,
    },
    {
      id: 860,
      name: 'apical (V3-V4)',
      parentId: 858,
      main: 1,
      weight: 1.5,
    },
    {
      id: 861,
      name: 'Repolarisation précoce (Point J surélevé avec aspect de rebond dans les dérivations inférieures et/ou latérales)',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 862,
      name: 'inférieur (DII-DIII-aVF)',
      parentId: 861,
      main: 1,
      weight: 1.5,
    },
    {
      id: 863,
      name: 'latéral bas (V5-V6)',
      parentId: 861,
      main: 1,
      weight: 1.5,
    },
    {
      id: 864,
      name: 'latéral haut (DI aVL)',
      parentId: 861,
      main: 1,
      weight: 1.5,
    },
    {
      id: 865,
      name: 'syndrome de repolarisation précoce',
      parentId: 861,
      main: 1,
      weight: 1.5,
    },
    {
      id: 866,
      name: 'Sus-décalage ST (ST+) pathologique',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 867,
      name: "Sus-décalage ST évocateur d'occlusion coronaire/syndrome coronaire aigü (SCA)",
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 871,
      name: 'antérieur (V1-V6)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 872,
      name: 'septal (V1-V2)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 873,
      name: 'apical (V3-V4)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 874,
      name: 'latéral bas (V5-V6)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 875,
      name: 'latéral haut (DI-VL)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 876,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 877,
      name: 'postéro-basal (V7-V8-V9)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 878,
      name: 'droite (V3R-V4R)',
      parentId: 867,
      main: 1,
      weight: 1.5,
    },
    {
      id: 879,
      name: 'Sus-décalage ST évocateur de péricardite/myocardite',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 881,
      name: 'antérieur (V1-V6)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 882,
      name: 'septal (V1-V2)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 883,
      name: 'apical (V3-V4)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 884,
      name: 'latéral bas (V5-V6)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 885,
      name: 'latéral haut (DI-VL)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 886,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 887,
      name: 'postéro-basal (V7-V8-V9)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 888,
      name: 'droite (V3R-V4R)',
      parentId: 879,
      main: 1,
      weight: 1.5,
    },
    {
      id: 889,
      name: 'Sus-décalage ST évocateur de Brugada',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 890,
      name: 'Sus-décalage ST typique de Brugada (Point J surélevé avec Sus-décalage ST ≥ 2 mm en V1 ou V2 en dôme ou triangle)',
      parentId: 889,
      main: 1,
      weight: 1.5,
    },
    {
      id: 891,
      name: 'Sus-décalage ST atypique en V1',
      parentId: 889,
      main: 1,
      weight: 1.5,
    },
    {
      id: 892,
      name: 'Sus-décalage ST évocateur de Takotsubo',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 893,
      name: 'antérieur (V1-V6)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 894,
      name: 'septal (V1-V2)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 895,
      name: 'apical (V3-V4)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 896,
      name: 'latéral bas (V5-V6)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 897,
      name: 'latéral haut (DI-VL)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 898,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 899,
      name: 'postéro-basal (V7-V8-V9)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 900,
      name: 'droite (V3R-V4R)',
      parentId: 892,
      main: 1,
      weight: 1.5,
    },
    {
      id: 901,
      name: "Sus-décalage ST évocateur d'anévrysme ventriculaire",
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 902,
      name: 'antérieur (V1-V6)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 903,
      name: 'septal (V1-V2)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 904,
      name: 'apical (V3-V4)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 905,
      name: 'latéral bas (V5-V6)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 906,
      name: 'latéral haut (DI-VL)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 907,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 908,
      name: 'postéro-basal (V7-V8-V9)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 909,
      name: 'droite (V3R-V4R)',
      parentId: 901,
      main: 1,
      weight: 1.5,
    },
    {
      id: 913,
      name: 'Sous-décalage ST pathologique',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 914,
      name: "Sous-décalage ST évocateur d'une pathologie coronaire (SCA)",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 915,
      name: 'diffus',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 916,
      name: 'antérieur',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 917,
      name: 'septal (V1-V2)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 918,
      name: 'apical (V3-V4)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 919,
      name: 'latéral bas (V5-V6)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 920,
      name: 'latéral haut (DI-VL)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 921,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 922,
      name: 'basal (V7-V8-V9)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 923,
      name: 'droite (V3R V4R)',
      parentId: 914,
      main: 1,
      weight: 1.5,
    },
    {
      id: 924,
      name: "Sous-décalage ST évocateur d'une ischémie fonctionnelle",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 926,
      name: 'diffus',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 927,
      name: 'antérieur',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 928,
      name: 'septal (V1-V2)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 929,
      name: 'apical (V3-V4)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 930,
      name: 'latéral bas (V5-V6)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 931,
      name: 'latéral haut (DI-VL)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 932,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 933,
      name: 'basal (V7-V8-V9)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 934,
      name: 'droite (V3R V4R)',
      parentId: 924,
      main: 1,
      weight: 1.5,
    },
    {
      id: 935,
      name: 'Sous-décalage ST secondaire à une hypertrophie ventriculaire',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 936,
      name: "Sous-décalage ST évocateur d'une anomalie métabolique",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 939,
      name: 'diffus',
      parentId: 936,
      main: 1,
      weight: 1.5,
    },
    {
      id: 940,
      name: "Sous-décalage ST évocateur d'origine médicamenteuse",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 944,
      name: 'diffus',
      parentId: 940,
      main: 1,
      weight: 1.5,
    },
    {
      id: 945,
      name: "Sous-décalage ST miroir d'un ST+",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 946,
      name: 'antérieur',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 947,
      name: 'septal (V1-V2)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 948,
      name: 'apical (V3-V4)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 949,
      name: 'latéral bas (V5-V6)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 950,
      name: 'latéral haut (DI-VL)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 951,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 952,
      name: 'basal (V7-V8-V9)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 953,
      name: 'droite (V3R V4R)',
      parentId: 945,
      main: 1,
      weight: 1.5,
    },
    {
      id: 954,
      name: "Sous-décalage ST évocateur d'une péricardite/myocardite",
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 955,
      name: 'antérieur',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 956,
      name: 'septal (V1-V2)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 957,
      name: 'apical (V3-V4)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 958,
      name: 'latéral bas (V5-V6)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 959,
      name: 'latéral haut (DI-VL)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 960,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 961,
      name: 'basal (V7-V8-V9)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 962,
      name: 'droite (V3R V4R)',
      parentId: 954,
      main: 1,
      weight: 1.5,
    },
    {
      id: 963,
      name: "Anomalie de repolarisation avec QRS large évocatrices d'ischémie myocardique (SCA)",
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 964,
      name: 'Anomalie de repolarisation secondaire à un QRS large (discordance appropriée)',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 965,
      name: "Anomalie de l'Onde T",
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 966,
      name: 'Onde T inversée (discordante avec la polarité du QRS)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 967,
      name: 'Onde T inversée physiologique',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 968,
      name: 'isolée en DIII',
      parentId: 967,
      main: 1,
      weight: 1.5,
    },
    {
      id: 969,
      name: "en V2-V3 (repolarisation de l'apex)",
      parentId: 967,
      main: 1,
      weight: 1.5,
    },
    {
      id: 970,
      name: "V1-V4 chez l'athlète d'origine africaine",
      parentId: 967,
      main: 1,
      weight: 1.5,
    },
    {
      id: 971,
      name: "Onde T inversée évocatrice d'effet Chatterjee",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 972,
      name: 'antérieure étendue',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 973,
      name: 'septale (V1-V2)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 974,
      name: 'apicale (V3-V4)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 975,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 976,
      name: 'inférieure (DII DIII avF)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 977,
      name: 'postérieure (V7-V8-V9)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 978,
      name: 'droite (V3R V4R)',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 979,
      name: 'diffuse',
      parentId: 971,
      main: 1,
      weight: 1.5,
    },
    {
      id: 980,
      name: "Onde T inversée évocatrice d'une cardiopathie",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 981,
      name: 'antérieure étendue',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 982,
      name: 'septale (V1-V2)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 983,
      name: 'apicale (V3-V4)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 984,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 985,
      name: 'inférieure (DII DIII avF)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 986,
      name: 'postérieure (V7-V8-V9)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 987,
      name: 'droite (V3R V4R)',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 988,
      name: 'diffuse',
      parentId: 980,
      main: 1,
      weight: 1.5,
    },
    {
      id: 989,
      name: "Onde T inversée écovatrice d'une pathologie coronaire (SCA)",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 990,
      name: 'antérieure étendue',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 991,
      name: 'septale (V1-V2)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 992,
      name: 'apicale (V3-V4)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 993,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 994,
      name: 'inférieure (DII DIII avF)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 995,
      name: 'postérieure (V7-V8-V9)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 996,
      name: 'droite (V3R V4R)',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 997,
      name: 'diffuse',
      parentId: 989,
      main: 1,
      weight: 1.5,
    },
    {
      id: 998,
      name: "Onde T inversée écovatrice d'une anomalie métabolique",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1000,
      name: "Onde T inversée écovatrice d'origine médicamenteuse",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1003,
      name: "Onde T inversée écovatrice d'un Tako-tsubo",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1004,
      name: "Onde T inversée écovatrice d'un épanchement péricardique",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1005,
      name: "Onde T inversée écovatrice d'une embolie pulmonaire",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1007,
      name: 'antérieure étendue',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1008,
      name: 'septale (V1-V2)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1009,
      name: 'apicale (V3-V4)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1010,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1011,
      name: 'inférieure (DII DIII avF)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1012,
      name: 'postérieure (V7-V8-V9)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1013,
      name: 'droite (V3R V4R)',
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1014,
      name: 'Onde T négative',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1015,
      name: 'Onde T négative physiologique',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1016,
      name: "V1-V3 chez le jeune adulte (pas d'onde T inversée)",
      parentId: 1015,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1017,
      name: 'antérieure étendue',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1018,
      name: 'septale (V1-V2)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1019,
      name: 'apicale (V3-V4)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1020,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1021,
      name: 'inférieure (DII DIII avF)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1022,
      name: 'postérieure (V7-V8-V9)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1023,
      name: 'droite (V3R V4R)',
      parentId: 1014,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1024,
      name: 'Onde T bifide',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1025,
      name: 'Onde T ample',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1026,
      name: 'Onde T plate',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1027,
      name: 'Onde U anormale (Onde U > onde T)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1028,
      name: 'Anomalie de la durée du QT',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1029,
      name: 'QT long',
      parentId: 1028,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1030,
      name: 'QT long secondaire',
      parentId: 1029,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1031,
      name: "QT long d'origine médicamenteuse",
      parentId: 1030,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1034,
      name: "QT long d'origine métabolique",
      parentId: 1030,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1041,
      name: 'QT long secondaire à une bradycardie',
      parentId: 1030,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1046,
      name: 'QT long congénital',
      parentId: 1029,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1049,
      name: 'QT long congénital de type 1',
      parentId: 1046,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1052,
      name: 'QT long congénital de type 2',
      parentId: 1046,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1055,
      name: 'QT long congénital de type 3',
      parentId: 1046,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1058,
      name: 'QT long congénital de type > 3',
      parentId: 1046,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1063,
      name: 'QT court (QTc ≤ 320 ms)',
      parentId: 1028,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1064,
      name: 'Anomalie métabolique',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1065,
      name: 'Hypokaliémie',
      parentId: 1064,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1069,
      name: 'Hyperkaliémie',
      parentId: 1064,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1074,
      name: 'Hypocalcémie',
      parentId: 1064,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1076,
      name: 'Hypercalcémie',
      parentId: 1064,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1078,
      name: 'sus-décalage ST pathologique',
      parentId: 1076,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1080,
      name: 'Hypothermie',
      parentId: 1064,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1085,
      name: "Onde J d'osborn",
      parentId: 1080,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1086,
      name: 'Médicamenteux / toxique',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1087,
      name: 'Antiarythmique de classe 1 (bloqueurs sodiques)',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1094,
      name: 'surdosage',
      parentId: 1087,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1095,
      name: 'imprégnation',
      parentId: 1087,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1096,
      name: 'Antiarythmique de classe 2 (bétabloquants)',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1100,
      name: 'surdosage',
      parentId: 1096,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1101,
      name: 'imprégnation',
      parentId: 1096,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1102,
      name: 'Antiarythmique de classe 3 (bloqueurs potassiques)',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1107,
      name: 'surdosage',
      parentId: 1102,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1108,
      name: 'imprégnation',
      parentId: 1102,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1109,
      name: 'Antiarythmique de classe 4 (bloqueurs calciques)',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1113,
      name: 'surdosage',
      parentId: 1109,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1114,
      name: 'imprégnation',
      parentId: 1109,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1115,
      name: 'Digitaliques',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1120,
      name: 'surdosage',
      parentId: 1115,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1121,
      name: 'imprégnation',
      parentId: 1115,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1122,
      name: 'Stabilisateurs de membrane',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1127,
      name: 'Inhibiteurs de la recapture de la sérotonine',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1128,
      name: 'surdosage',
      parentId: 1127,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1129,
      name: 'imprégnation',
      parentId: 1127,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1130,
      name: 'Neuroleptiques',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1131,
      name: 'surdosage',
      parentId: 1130,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1132,
      name: 'imprégnation',
      parentId: 1130,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1133,
      name: 'Anti-dépresseurs tricycliques',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1135,
      name: 'surdosage',
      parentId: 1133,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1136,
      name: 'imprégnation',
      parentId: 1133,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1137,
      name: 'Médicamenteux autre',
      parentId: 1086,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1138,
      name: 'Cardiopathie / contexte',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1139,
      name: 'Absence de cardiopathie (coeur sain)',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1140,
      name: 'Amylose',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1142,
      name: 'Athlète / sportif',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1147,
      name: 'Cardiomyopathie dilatée',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1148,
      name: 'Cardiomyopathie hypertrophique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1151,
      name: 'ST- secondaire à une hypertrophie ventriculaire',
      parentId: 1148,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1152,
      name: 'Cardiomyopathie restrictive',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1153,
      name: 'Cardiopathie arythmogène (dont dysplasie arythmogène du ventricule droit: DAVD)',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1154,
      name: 'Onde Epsilon',
      parentId: 1153,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1157,
      name: 'Cardiopathie autre',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1158,
      name: 'Cardiopathie congénitale',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1159,
      name: 'Tétrallogie de Fallot',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1162,
      name: 'Transposition des gros vaisceaux',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1165,
      name: 'Communication inter-ventriculaire',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1168,
      name: 'Communication inter-auriculaire',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1172,
      name: 'Double discordance',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1175,
      name: 'Ventricule unique',
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1178,
      name: "Maladie d'Ebstein",
      parentId: 1158,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1183,
      name: 'Cardiopathie ischémique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1185,
      name: 'Cardiopathie rythmique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1187,
      name: 'Cardiopathie toxique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1188,
      name: 'Cardiopathie aux anthracyclines',
      parentId: 1187,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1189,
      name: 'Cardiopathie chimiothérapie autre',
      parentId: 1187,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1190,
      name: 'Cardiopathie alcoolique',
      parentId: 1187,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1191,
      name: 'Coeur pulmonaire aigü (embolie pulmonaire)',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1196,
      name: 'Coeur pulmonaire chronique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1199,
      name: 'Dysjonction annulaire mitrale',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1201,
      name: 'Epanchement péricardique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1203,
      name: 'Hémochromatose',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1205,
      name: 'Hypertension artérielle pulmonaire (HTAP)',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1208,
      name: 'Insuffisance aortique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1210,
      name: 'Insuffisance mitrale',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1212,
      name: 'Laminopathies',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1215,
      name: 'Maladie de Danon',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1216,
      name: 'Maladie de Fabry',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1218,
      name: 'Myocardite',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1219,
      name: 'sus-décalage ST pathologique',
      parentId: 1218,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1221,
      name: 'Myopathie de Steinert',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1224,
      name: 'Rétrécissement aortique',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1226,
      name: 'Rétrécissement mitral',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1228,
      name: 'Tako-tsubo',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1230,
      name: 'sus-décalage ST pathologique',
      parentId: 1228,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1232,
      name: 'Tamponnade',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1233,
      name: 'Alternance electrique',
      parentId: 1232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1235,
      name: 'Transplantation cardiaque',
      parentId: 1138,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1237,
      name: 'ECG normal',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1271,
      name: 'bigéminisme',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1272,
      name: 'trigéminisme',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1273,
      name: 'doublet',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1274,
      name: 'triplet',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1275,
      name: 'salve',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1276,
      name: 'bigéminisme',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1277,
      name: 'trigéminisme',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1278,
      name: 'doublet',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1279,
      name: 'triplet',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1280,
      name: 'salve',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1281,
      name: 'bigéminisme',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1282,
      name: 'trigéminisme',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1283,
      name: 'doublet',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1284,
      name: 'triplet',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1285,
      name: 'salve',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1286,
      name: 'bigéminisme',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1287,
      name: 'trigéminisme',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1288,
      name: 'doublet',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1289,
      name: 'triplet',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1290,
      name: 'salve',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1291,
      name: 'bigéminisme',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1292,
      name: 'trigéminisme',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1293,
      name: 'doublet',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1294,
      name: 'triplet',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1295,
      name: 'salve',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1296,
      name: 'bigéminisme',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1297,
      name: 'trigéminisme',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1298,
      name: 'doublet',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1299,
      name: 'triplet',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1300,
      name: 'salve',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1301,
      name: 'bigéminisme',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1302,
      name: 'trigéminisme',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1303,
      name: 'doublet',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1304,
      name: 'triplet',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1305,
      name: 'salve',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1306,
      name: 'bigéminisme',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1307,
      name: 'trigéminisme',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1308,
      name: 'doublet',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1309,
      name: 'triplet',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1310,
      name: 'salve',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1311,
      name: 'bigéminisme',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1312,
      name: 'trigéminisme',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1313,
      name: 'doublet',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1314,
      name: 'triplet',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1315,
      name: 'salve',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1316,
      name: 'bigéminisme',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1317,
      name: 'trigéminisme',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1318,
      name: 'doublet',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1319,
      name: 'triplet',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1320,
      name: 'salve',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1321,
      name: 'bloquée',
      parentId: 562,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1322,
      name: 'bigéminisme',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1323,
      name: 'trigéminisme',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1324,
      name: 'doublet',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1325,
      name: 'triplet',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1326,
      name: 'salve',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1327,
      name: 'bloquée',
      parentId: 563,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1328,
      name: 'bigéminisme',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1329,
      name: 'trigéminisme',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1330,
      name: 'doublet',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1331,
      name: 'triplet',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1332,
      name: 'salve',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1333,
      name: 'bloquée',
      parentId: 570,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1425,
      name: 'péri-cicatriciel post chirurgie cardiaque',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1426,
      name: 'péri-mitral',
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1427,
      name: "du toit de l'OG",
      parentId: 379,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1428,
      name: 'péri-cicatriciel post chirurgie cardiaque',
      parentId: 391,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1429,
      name: 'péri-cicatriciel post chirurgie cardiaque',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1430,
      name: 'péri-mitral',
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1431,
      name: "du toit de l'OG",
      parentId: 403,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1551,
      name: 'phénomène R sur T',
      parentId: 583,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1554,
      name: 'phénomène R sur T',
      parentId: 584,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1556,
      name: 'phénomène R sur T',
      parentId: 603,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1559,
      name: 'phénomène R sur T',
      parentId: 622,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1562,
      name: 'phénomène R sur T',
      parentId: 641,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1565,
      name: 'phénomène R sur T',
      parentId: 660,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1568,
      name: 'phénomène R sur T',
      parentId: 679,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1571,
      name: 'phénomène R sur T',
      parentId: 698,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1574,
      name: 'phénomène R sur T',
      parentId: 717,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1769,
      name: 'phénomène R sur T',
      parentId: 1029,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1856,
      name: 'Tachycardie ventriculaire (TV) polymorphe',
      parentId: 338,
      main: 1,
      weight: 1.5,
    },
    {
      id: 1857,
      name: 'Tachycardie ventriculaire bidirectionnelle',
      parentId: 338,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2045,
      name: 'Anomalie de repolarisation secondaire à une tachycardie',
      parentId: 856,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2232,
      name: "Onde T inversée évocatrice d'une ischémie fonctionnelle",
      parentId: 966,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2233,
      name: 'secondaire à une tachycardie',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2234,
      name: 'antérieure étendue',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2235,
      name: 'septale (V1-V2)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2236,
      name: 'apicale (V3-V4)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2237,
      name: 'latérale (V5-V6 Di aVL)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2238,
      name: 'inférieure (DII DIII avF)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2239,
      name: 'postérieure (V7-V8-V9)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2240,
      name: 'droite (V3R V4R)',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2241,
      name: 'diffuse',
      parentId: 965,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2500,
      name: 'secondaire à une tachycardie',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2501,
      name: 'antérieure étendue',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2503,
      name: 'septale (V1-V2)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2504,
      name: 'apicale (V3-V4)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2505,
      name: 'latérale bas (V5-V6)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2506,
      name: 'latérale haut (DI-VL)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2507,
      name: 'inférieure (DIII-VF-DII)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2508,
      name: 'basale (V7-V8-V9)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2509,
      name: 'droite (V3R V4R)',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2510,
      name: 'diffuse',
      parentId: 2232,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2685,
      name: 'étendu',
      parentId: 861,
      main: 1,
      weight: 1.5,
    },
    {
      id: 2860,
      name: 'Axe des QRS',
      parentId: 821,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3138,
      name: 'Arrêt anomalie de rythme',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3139,
      name: 'Début anomalie de rythme',
      parentId: null,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3321,
      name: 'diffus',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3322,
      name: 'antérieur',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3323,
      name: 'septal (V1-V2)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3324,
      name: 'apical (V3-V4)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3325,
      name: 'latéral bas (V5-V6)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3326,
      name: 'latéral haut (DI-VL)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3327,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3328,
      name: 'basal (V7-V8-V9)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3329,
      name: 'droite (V3R V4R)',
      parentId: 913,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3504,
      name: 'antérieur (V1-V6)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3505,
      name: 'septal (V1-V2)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3506,
      name: 'apical (V3-V4)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3507,
      name: 'latéral bas (V5-V6)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3508,
      name: 'latéral haut (DI-VL)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3509,
      name: 'inférieur (DIII-VF-DII)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3510,
      name: 'postéro-basal (V7-V8-V9)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3511,
      name: 'droite (V3R-V4R)',
      parentId: 866,
      main: 1,
      weight: 1.5,
    },
    {
      id: 3789,
      name: 'Manoeuvres vagales',
      parentId: 1,
      main: 1,
      weight: 1.5,
    },
  ]
  async run() {
    // Write your database queries inside the run method
    await Tag.createMany(this.datas)
  }
}
